[package]
name = "password"
version = "0.1.0"
description = "Generate passwords"
authors = ["Kyle Clemens <git@kyleclemens.com>"]
edition = "2018"

[dependencies]
atty = "0.2"
clap = "2"
rand = "0.6"
